# Generated by Django 4.1.1 on 2022-10-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='no-avatar.jpg', null=True, upload_to='user/users'),
        ),
    ]
