# Generated by Django 4.0 on 2022-10-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishe_1', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InstructionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'InstructionModel',
                'verbose_name_plural': 'InstructionModels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuantityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'QuantityModel',
                'verbose_name_plural': 'QuantityModels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecipesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/img')),
                ('link_video', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('VEGANA', 'Vegana'), ('CARNE', 'Carne'), ('POSTRE', 'Postre')], max_length=12)),
                ('timeday', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=12)),
                ('difficulty', models.CharField(choices=[('Fácil', 'Fácil'), ('Normal', 'Normal'), ('Dificíl', 'Dificíl')], max_length=10)),
                ('recipes_time', models.IntegerField()),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredients')),
                ('instruction', models.ManyToManyField(to='recipes.InstructionModel')),
                ('quantity', models.ManyToManyField(to='recipes.QuantityModel')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipesmodel')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['id'],
            },
        ),
    ]
