# Generated by Django 4.1.1 on 2022-10-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredients'),
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='image',
            field=models.ImageField(blank=True, default='media/user/users/no-avatar.jpg', null=True, upload_to='recipes/img'),
        ),
    ]
