# Generated by Django 4.1.1 on 2022-10-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipesmodel_description_recipesmodel_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesmodel',
            name='image',
            field=models.ImageField(blank=True, default='user/users/no-avatar.jpg', null=True, upload_to='recipes/img'),
        ),
    ]
