# Generated by Django 4.1.1 on 2022-10-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipesmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesmodel',
            name='image',
            field=models.ImageField(blank=True, default='no-avatar.jpg', null=True, upload_to='recipes/img'),
        ),
    ]
