# Generated by Django 4.0 on 2022-10-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipesmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesmodel',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='number_of_dishes',
            field=models.IntegerField(),
        ),
    ]
