# Generated by Django 4.1.1 on 2022-10-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipesmodel_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesmodel',
            name='number_of_dishes',
        ),
    ]
