# Generated by Django 4.1.1 on 2022-10-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipesmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesmodel',
            name='timeday',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=12, null=True),
        ),
    ]
