# Generated by Django 4.1.1 on 2022-10-17 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipesmodel_timeday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesmodel',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients'),
            preserve_default=False,
        ),
    ]
