# Generated by Django 4.1.1 on 2022-10-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipesmodel_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='dishe_2',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='dishe_3',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='dishe_4',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='dishe_5',
        ),
        migrations.RemoveField(
            model_name='recipesmodel',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredients'),
        ),
    ]
