# Generated by Django 4.1.1 on 2022-10-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_quantitymodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'InstructionModel',
                'verbose_name_plural': 'InstructionModels',
                'ordering': ['id'],
            },
        ),
    ]
