# Generated by Django 4.1.1 on 2022-10-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_instructionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
