# Generated by Django 4.1.1 on 2022-10-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_recipesmodel_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesmodel',
            name='difficulty',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Normal', 'Normal'), ('Dificíl', 'Dificíl')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipesmodel',
            name='timeday',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
